import { throwError } from "rxjs";
import { catchError } from "rxjs/operators";

throwError("Kaboom!").pipe(
  catchError((error: unknown) => console.error(error))
);
throwError("Kaboom!").pipe(
  catchError(function (error: unknown) { console.error(error); })
);

throwError("Kaboom!").pipe(
  catchError((error: unknown) => console.error(error))
);
throwError("Kaboom!").pipe(
  catchError(function (error: unknown) { console.error(error); })
);

throwError("Kaboom!").pipe(
  catchError((error: any) => console.error(error))
);
throwError("Kaboom!").pipe(
  catchError(function (error: any) { console.error(error); })
);

